services:
  - docker
script:
  - ls -alh
deploy:
  - provider: script
    skip_cleanup: true
    script: echo "On master" && echo $TRAVIS_BRANCH
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: echo "On tag" && echo $TRAVIS_TAG && echo $TRAVIS_BRANCH
    on:
      tags: true
